### Fancy indexing

In [16]:
import numpy as np 

In [17]:
range_array = np.arange(10)
print("range_array:",range_array)
print("range_array shape:",range_array.shape)
print("range_array dtype:",range_array.dtype)

range_array: [0 1 2 3 4 5 6 7 8 9]
range_array shape: (10,)
range_array dtype: int32


### Boolean indexing

In [19]:
array1d = np.arange(10)
print(array1d)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
print(array1d > 5)
result_bool = print(array1d > 5)
print("result_bool :\n",result_bool)
print("result_bool :\n",type(result_bool))

[False False False False False False  True  True  True  True]
[False False False False False False  True  True  True  True]
result_bool :
 None
result_bool :
 <class 'NoneType'>


In [21]:
print("array1d:\n", array1d)
array3 = array1d[array1d > 5]
print("array3:\n", array3)

array1d:
 [0 1 2 3 4 5 6 7 8 9]
array3:
 [6 7 8 9]


In [27]:
#boolean 값으로 구성된 배열 생성하기
#                  --boolean index --
boolean_indexes_array = \
    np.array([False, False, False, False, False,  True, True, True, True])
'''
array1d:(원래의 배열)
 [0 1 2 3 4 5 6 7 8 9]
'''
array3 = array1d[boolean_indexes_array]
print("array3(boolean_indexing - [array1d > 5]):\n",array3)

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 9

In [31]:
#np.array([5,6,7,8]) <-- index 값(5,6,7,8)으로 이루어진 배열
indexes_array = np.array([5,6,7,8])
print("indexes_array:\n",indexes_array)
'''
array1d:(원래의 배열)
 [0 1 2 3 4 5 6 7 8 9]
'''

array4 = array1d[indexes_array]
print("array4:\n",array4)
print("-"*50)

array1d = np.arange(1,10)
print("indexes_array:\n",indexes_array)
array5 = array1d[indexes_array]
print("array5:\n",array5)

indexes_array:
 [5 6 7 8]
array4:
 [6 7 8 9]
--------------------------------------------------
indexes_array:
 [5 6 7 8]
array5:
 [6 7 8 9]


In [34]:
array1d = np.arange(1,10)
print("array1d:\n", array1d)

result = []
for i in range(0, 9):
    if array1d[i] > 5:
        result.append(array1d[i])
        
result_array = np.array(result)
print("result_array:\n", result_array)

print("array1d[array1d >5] :\n", array1d[array1d>5])

array1d:
 [1 2 3 4 5 6 7 8 9]
result_array:
 [6 7 8 9]
array1d[array1d >5] :
 [6 7 8 9]


3 배열(2차원 배열 - 행렬) 정렬하기
* sort() 함수 / ndarray 의 sort() 메소드
*argsort() 함수

In [42]:
origin_array = np.array([3,1,9,5])
print("원래의배열 :\n", origin_array)

print("-"*50)
# np.sort()함수로 정렬하기
print("-- np.sort() 메소드로 정렬하기 :원래의 배열이 변형 안됨")
print("-- 정렬된 배열이 새로 생성 됨")

sort_array1 = np.sort(origin_array)
print("원래의배열 :\n", origin_array)
print("sort_array1 :\n", sort_array1)

#ndarray 의 sort() 메소드로 정렬하기
print("-- ndarray의 sort() 메소드로 정렬하기 :원래의 배열이 변형됨")
print("-- 정렬된 배열이 새로 생성 되지 않음")

sort_array2 = origin_array.sort()
print("원래의배열 :\n", origin_array)
print("sort_array2 :\n", sort_array2)

원래의배열 :
 [3 1 9 5]
--------------------------------------------------
-- np.sort() 메소드로 정렬하기 :원래의 배열이 변형 안됨
-- 정렬된 배열이 새로 생성 됨
원래의배열 :
 [3 1 9 5]
sort_array1 :
 [1 3 5 9]
-- ndarray의 sort() 메소드로 정렬하기 :원래의 배열이 변형됨
-- 정렬된 배열이 새로 생성 되지 않음
원래의배열 :
 [1 3 5 9]
sort_array2 :
 None


* 내림차순으로 정렬하기 - slicing(step : -1)

In [43]:
# np.sort() 함수로 내림차순 정렬하기
sort_array1_descending = np.sort(origin_array)[::-1]
print("sort_array1_descending:\n",sort_array1_descending)

sort_array1_descending:
 [9 5 3 1]


* 2차원 배열 행방향 정렬 / 열방향 정렬
* axis = 0 : 행방향      
* axis = 1 : 열방향

In [47]:
array2d = np.array([[8, 20],
                    [5, 2]])
sort_array2d_row = np.sort(array2d, axis=0)
print("행방향(행이 축이 됨) 정렬:\n", sort_array2d_row)

sort_array2d_col = np.sort(array2d, axis=1)
print("열방향(열이 축이 됨) 정렬 :\n", sort_array2d_col)

행방향(행이 축이 됨) 정렬:
 [[ 5  2]
 [ 8 20]]
열방향(열이 축이 됨) 정렬 :
 [[ 8 20]
 [ 2  5]]


* argsort()

In [53]:
origin_array = np.array([3,1,9,5])
print("원래의배열 :\n", origin_array)
print("원래의 index :\n", np.array([0,1,2,3]))

sort_array = np.sort(origin_array)
print("sort_array(정렬된 숫자들):\n", sort_array)
argsort_indexes_array = np.argsort(origin_array)
print("argsort_indexes_array(정렬되기 전 숫자들의 index) :\n",argsort_indexes_array)

원래의배열 :
 [3 1 9 5]
원래의 index :
 [0 1 2 3]
sort_array(정렬된 숫자들):
 [1 3 5 9]
argsort_indexes_array(정렬되기 전 숫자들의 index) :
 [1 0 3 2]


In [61]:
origin_array = np.array([6,3,8,2])
print("원래의 행렬:\n", origin_array)
print("원래의 인덱스:\n", np.array([0,1,2,3]))
print("내림차순 정렬 :\n",np.sort(origin_array)[::-1])
print("인덱스가 정렬전 숫자들의 자리에 재배치된 인덱스")
print("정렬 전 인덱스 :\n",np.argsort(origin_array)[::-1])

원래의 행렬:
 [6 3 8 2]
원래의 인덱스:
 [0 1 2 3]
내림차순 정렬 :
 [8 6 3 2]
인덱스가 정렬전 숫자들의 자리에 재배치된 인덱스
정렬 전 인덱스 :
 [2 0 1 3]


In [81]:
student_array = np.array(["이순신", "강감찬", "대조영", "유관순", "안중근"])
score_array = np.array([85, 92, 84, 99, 76])

print("score_array(원본):\n",score_array)
print("원본 인덱스 :\n", np.array([0,1,2,3,4]))
sort_score = np.sort(score_array)
print("sort_scor(정렬) :\n", sort_score)
sort_indexes = np.argsort(score_array)
print("sort_indexes :\n",sort_indexes)
print("-"*40)

#성적 오름차순으로 이름 출력하기
print("-- 성적 오름차순으로 이름 출력하기 --")
print(student_array[sort_indexes])
print("-"*40)

#성적 내림차순으로 이름 출력하기
print("-- 성적 내림차순으로 이름 출력하기 --")
sort_indexes_descending = np.argsort(score_array)[::-1]
print(student_array[sort_indexes_descending])
print("-"*40)

score_array(원본):
 [85 92 84 99 76]
원본 인덱스 :
 [0 1 2 3 4]
sort_scor(정렬) :
 [76 84 85 92 99]
sort_indexes :
 [4 2 0 1 3]
----------------------------------------
-- 성적 오름차순으로 이름 출력하기 --
['안중근' '대조영' '이순신' '강감찬' '유관순']
----------------------------------------
-- 성적 내림차순으로 이름 출력하기 --
['유관순' '강감찬' '이순신' '대조영' '안중근']
----------------------------------------


In [71]:
array1 = np.arange(1,10)
print(array1)
print(array1[np.array([5,6,7,8])])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


4 행렬의 합(내적) 구하기 np.dot(행렬1, 행렬2) 함수

In [86]:
array_a = np.array([[1,2,3],
                    [4,5,6]])
array_b = np.array([[7, 8],
                    [9,10],
                    [11,12]])
product_array = np.dot(array_a, array_b)
print("행렬의 내적 :\n",product_array)

행렬의 내적 :
 [[ 58  64]
 [139 154]]


5 전치 행렬 구하기 (transposed matrix) - np.transpose(행렬) 함수 사용

In [89]:
array_a = np.array([[1, 2],
                    [3, 4], 
                    [5, 6]])
print("array_a:\n",array_a)
transpose_matrix = np.transpose(array_a)
print("array_a 의 전치행렬:\n", transpose_matrix)

array_a:
 [[1 2]
 [3 4]
 [5 6]]
array_a 의 전치행렬:
 [[1 3 5]
 [2 4 6]]


In [92]:
array_a = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print("array_a\n:",array_a)
transpose_matrix = np.transpose(array_a)
print("array_a 의 전치행렬:\n", transpose_matrix)

array_a
: [[1 2 3]
 [4 5 6]
 [7 8 9]]
array_a 의 전치행렬:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
