### Numpy ndarray
* ndarray 생성하기 - np.array()

In [2]:
import numpy as np

In [3]:
# 일차원 배열
list1 = [1,2,3]
print("list1 :", list1)
print("list1 :", type(list1))

array1 = np.array(list1)
print("array1 :", array1)
print("array1 :", type(array1))

list1 : [1, 2, 3]
list1 : <class 'list'>
array1 : [1 2 3]
array1 : <class 'numpy.ndarray'>


* ndarray의 shape(형태 - 배열의 구조) / 차원(일차원, 이차원, 삼차원...)

In [4]:
array1 = np.array([1,2,3,4,5])
print("array1       :", array1)
print("array1 타입  :", type(array1))
print("array1 shape :", array1.shape)

array1       : [1 2 3 4 5]
array1 타입  : <class 'numpy.ndarray'>
array1 shape : (5,)


In [6]:
# 이차원 배열
array2 = np.array([
                    [1, 2, 3],
                    [4, 5, 6]
                    ])
print("array2       :\n", array2)
print("array2 타입  :", type(array2))
print("array2 shape :", array2.shape)

array2       :
 [[1 2 3]
 [4 5 6]]
array2 타입  : <class 'numpy.ndarray'>
array2 shape : (2, 3)


In [9]:
# 이차원 배열

array3 = np.array([[1, 2, 3, 4, 5]])
print("array3 :", array3)
print("array3 타입 :", type(array3))
print("array3 shape :", array3.shape)

array3 : [[1 2 3 4 5]]
array3 타입 : <class 'numpy.ndarray'>
array3 shape : (1, 5)


In [35]:
print(f"array1 : {array1.ndim} 차원\n array2 : {array2.ndim} 차원\n array3 : {array3.ndim} 차원\n")

array1 : 1 차원
 array2 : 2 차원
 array3 : 2 차원



* ndarry 속에 들어있는 값의 data tyep

In [13]:
list1 = [1 ,2 ,3 ,4 ,5]
print("list1 :", list1)
print("list1 :", type(list1))

array1 = np.array(list1)
print("array1 :", array1)
print("array1 타입 :", type(array1))
print("array1 속에 들어잇는 값의 data 타입 :", array1.dtype)

list1 : [1, 2, 3, 4, 5]
list1 : <class 'list'>
array1 : [1 2 3 4 5]
array1 타입 : <class 'numpy.ndarray'>
array1 속에 들어잇는 값의 data 타입 : int32


In [36]:
array_int = np.array([1, 2, 3, 4, 5])
array_float = array_int.astype("float64")

print("array_int :", array_int)
print("array_int :", array_int.dtype)
print("array_float :", array_float)
print("array_float d타입 :", array_float.dtype)

array_int : [1 2 3 4 5]
array_int : int32
array_float : [1. 2. 3. 4. 5.]
array_float d타입 : float64


In [37]:
# array_float = array_int.astype("float64")
array_int2 = array_float.astype("int32")

print("array_int2 :", )

array_int2 :


In [38]:
array_float2 = np.array([1.2 2.3 3.4 4.5])
print("array_float2 :", array_float2)
print("array_float2 d타입 :", array_float2.dtype)

array_int3 = array_float3.astype("int32")
print("array_float3 :", array_float3)
print("array_float3 d타입 :", array_float3.dtype)

SyntaxError: invalid syntax (Temp/ipykernel_23348/3722096678.py, line 1)

### 이차원 배열의 요소들을 axls를 지정해서 연산하기
* axis = 0 : 행이 축이 됨
* axis = 1 :열이 축이 됨

In [18]:
array2 = np.array([
                  [1 ,2 ,3 ,4 ,5],
                  [6 ,7 ,8 ,9 ,10]
                  ])
print("array2.sum():",array2.sum())
print("array2.sum(axis=0):",array2.sum(axis=0))
print("array2.sum(axis=1):",array2.sum(axis=1))

array2.sum(): 55
array2.sum(axis=0): [ 7  9 11 13 15]
array2.sum(axis=1): [15 40]


3 ndarray 생성하는 여러가지 방법들
* np.arange()
* np.zeros()
* np.pones()

In [ ]:
#arange()

In [78]:
range_array = np.arange(10)
print("range_array:",range_array)
print("range_array shape:",range_array.shape)
print("range_array dtype:",range_array.dtype)

range_array: [0 1 2 3 4 5 6 7 8 9]
range_array shape: (10,)
range_array dtype: int32


In [24]:
# zeros()

zero_array = np.zeros((3,3),dtype="int32")
print("zero_array:",zero_array)
print("zero_array shape:",zero_array.shape)
print("zero_array dtype:",zero_array.dtype)

zero_array: [[0 0 0]
 [0 0 0]
 [0 0 0]]
zero_array shape: (3, 3)
zero_array dtype: int32


In [26]:
zero_array = np.zeros((3,3))
print("zero_array:",zero_array)
print("zero_array shape:",zero_array.shape)
print("zero_array dtype:",zero_array.dtype)

zero_array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
zero_array shape: (3, 3)
zero_array dtype: float64


In [28]:
#ones
ones_array = np.zeros((3, 6), dtype="int32")
print("ones_array:",ones_array)
print("ones_array shape:",ones_array.shape)
print("ones_array dtype:",ones_array.dtype)

ones_array: [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
ones_array shape: (3, 6)
ones_array dtype: int32


* ndarray.reshape() 메소드 - shape를 재설정함

In [34]:
array1 = np.arange(10)
print("array1:\n",array1)

array2 = array1.reshape(2, 5)
print("array2:\n",array2)

array3 = array1.reshape(5, 2)
print("array3:\n",array3)

# 데이터 개수에 맞는 행과 열을 지정해 주어야만 함
#ValueError: cannot reshape array of size 10 into shape (3,3)
#array4 = array1.reshape(3, 3)
#print("array4:\n",array4)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### reshape()의 argument로 -1 설정하기
* argument 둘 다 -1로 지정할 수는 없음

In [43]:
array1 = np.arange(10)
print("array1:\n",array1)

#reshpae(-1, 5): 열을 5로 지정하고 행은 이에 맞추어서 자동으로 지정됨
array2 = array1.reshape(-1, 5)
print("array2의 shape:\n",array2.shape)
print("array2 :\n",array2)

#reshpae(5, -1): 5 X 2
#행을 5로 지정하고 열은 이에 맞추어서 자동으로 지정됨
array3 = array1.reshape(5, -1)
print("array3의 shape:\n",array3.shape)
print("array3 :\n",array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2의 shape:
 (2, 5)
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3의 shape:
 (5, 2)
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [46]:
#1차원 배열
array1 = np.arange(5)
print("array1의 shape:\n",array1.shape)
print("array1 :\n",array1)

# 5 X 1 의 2차원 배열
array2 = array1.reshape(-1, 1)
print("array2의 shape:\n",array2.shape)
print("array2 :\n",array2)

# 2 차원 배열을 1차원 배열로 변환함
array3 = array1.reshape(-1, )
print("array3의 shape:\n",array3.shape)
print("array3 :\n",array3)

array1의 shape:
 (5,)
array1 :
 [0 1 2 3 4]
array2의 shape:
 (5, 1)
array2 :
 [[0]
 [1]
 [2]
 [3]
 [4]]
array3의 shape:
 (5,)
array3 :
 [0 1 2 3 4]


### ndarray 에서 indexing 하기

In [51]:
array1 = np.arange(10)
print("array1 :\n",array1)

array1_1 = np.arange(start=1, stop=10)
print("array1_1 :\n",array1_1)

array1_2 = np.arange(1, 10)
print("array1_2 :\n",array1_2)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array1_1 :
 [1 2 3 4 5 6 7 8 9]
array1_2 :
 [1 2 3 4 5 6 7 8 9]


In [59]:
array1_2 = np.arange(1, 10)

result = array1_2[2]
print("result :", result)
print("result :", type(result))

result2 = array1_2[-1]
print("result2 :", result2)
result3 = array1_2[-2]
print("result3 :", result3)

print("array1_2 :\n",array1_2)
array1_2[0] = 9
array1_2[8] = 1
print("array1_2 :\n",array1_2)

result : 3
result : <class 'numpy.int32'>
result2 : 9
result3 : 8
array1_2 :
 [1 2 3 4 5 6 7 8 9]
array1_2 :
 [9 2 3 4 5 6 7 8 1]


In [60]:
#reshape()를 사용해서 2차원 배열로 변환하기
array1_2_2d = array1_2.reshape(3, 3)

'''
array1_2_2d
 [[9 2 3]
 [4 5 6]
 [7 8 1]]
'''
print("array1_2_2d[0, 0]:",array1_2_2d[0,0])
print("array1_2_2d[1, 1]:",array1_2_2d[1,1])
print("array1_2_2d[2, 2]:",array1_2_2d[2,2])
print("array1_2_2d[0, 2]:",array1_2_2d[0,2])

print("-"*40)
print("array1_2_2d :\n",array1_2_2d)
print("array1_2_2의 shape :",array1_2_2d.shape)

array1_2_2d[0, 0]: 9
array1_2_2d[1, 1]: 5
array1_2_2d[2, 2]: 1
array1_2_2d[0, 2]: 3
----------------------------------------
array1_2_2d :
 [[9 2 3]
 [4 5 6]
 [7 8 1]]
array1_2_2의 shape : (3, 3)


In [63]:
'''
array1_2_2d
 [[9 2 3]
 [4 5 6]
 [7 8 1]]
'''
print("array1_2_2d[0, 0]:",array1_2_2d[0,0])
print("array1_2_2d[1, 1]:",array1_2_2d[1,1])
print("array1_2_2d[2, 2]:",array1_2_2d[2,2])
print("array1_2_2d[0, 2]:",array1_2_2d[0,2])
print("-"*40)

print("array1_2_2d[0][0]:",array1_2_2d[0][0])
print("array1_2_2d[1][1]:",array1_2_2d[1][1])
print("array1_2_2d[2][2]:",array1_2_2d[2][2])
print("array1_2_2d[0][2]:",array1_2_2d[0][2])

print("-"*40)
print("array1_2_2d :\n",array1_2_2d)
print("array1_2_2의 shape :",array1_2_2d.shape)

array1_2_2d[0, 0]: 9
array1_2_2d[1, 1]: 5
array1_2_2d[2, 2]: 1
array1_2_2d[0, 2]: 3
----------------------------------------
array1_2_2d[0][0]: 9
array1_2_2d[1][1]: 5
array1_2_2d[2][2]: 1
array1_2_2d[0][2]: 3
----------------------------------------
array1_2_2d :
 [[9 2 3]
 [4 5 6]
 [7 8 1]]
array1_2_2의 shape : (3, 3)


6 ndarray 에서 slicing 하기

In [70]:
array1 = np.arange(1, 10)
print("array1.shape:", array1.shape)
print("array1 type:", type(array1))
print("array1.:\n", array1)
print("-"*40)

array2 = array1[0:3]
print("array2.shape:", array2.shape)
print("array2 type:", type(array2))
print("array2.:\n", array2)
print("-"*40)

array3 = array1[:3]
print("array3.shape:", array3.shape)
print("array3 type:", type(array3))
print("array3.:\n", array3)
print("-"*40)

array4 = array1[3:]
print("array4.shape:", array4.shape)
print("array4 type:", type(array4))
print("array4.:\n", array4)
print("-"*40)

array5 = array1[:]
print("array5.shape:", array5.shape)
print("array5 type:", type(array5))
print("array5.:\n", array5)
print("-"*40)

array1.shape: (9,)
array1 type: <class 'numpy.ndarray'>
array1.:
 [1 2 3 4 5 6 7 8 9]
----------------------------------------
array2.shape: (3,)
array2 type: <class 'numpy.ndarray'>
array2.:
 [1 2 3]
----------------------------------------
array3.shape: (3,)
array3 type: <class 'numpy.ndarray'>
array3.:
 [1 2 3]
----------------------------------------
array4.shape: (6,)
array4 type: <class 'numpy.ndarray'>
array4.:
 [4 5 6 7 8 9]
----------------------------------------
array5.shape: (9,)
array5 type: <class 'numpy.ndarray'>
array5.:
 [1 2 3 4 5 6 7 8 9]
----------------------------------------


In [77]:
array2d = array1.reshape(3, 3)
print("array2d.shape:", array2d.shape)
print("array2d type:", type(array2d))
print("array2d.:\n", array2d)
print("-"*40)

# 1, 2, 행 X 1, 2 열
print("array2d[0:2, 0:2]:\n",array2d[0:2, 0:2])
print("-"*40)

# 1, 2, 행 X 1, 2, 3 열
print("array2d[1:3, 0:3]:\n",array2d[1:3, 0:3])
print("-"*40)

# 1, 2, 행 X 1, 2, 3 열 : 시작과 끝을 생략하면 처음부터 끝까지
print("array2d[1:3, :]:\n",array2d[1:3, :])
print("-"*40)

# 1, 2, 3 행 X 1, 2, 3 열 : 시작과 끝을 생략하면 처음부터 끝까지
print("array2d[:, :]:\n",array2d[:, :])
print("array2d[0:3, 0:3]:\n",array2d[0:3, 0:3])
print("-"*40)

# 1, 2 행 X 2, 3 열
print("array2d[:2, 1:]:\n",array2d[:2, 1:])
print("array2d[0:2, 1:3]:\n",array2d[0:2, 1:3])

# 1, 2 행 X 1열 : 열을 하나만 지정하면 1 차원 배열로 됨
print("array2d[:2, 0].shape:",array2d[:2, 0].shape)
print("array2d[:2, 0].shape :",array2d[:2, 0].shape)
print("array2d[0:2, 0].:\n",array2d[0:2, 0])

array2d.shape: (3, 3)
array2d type: <class 'numpy.ndarray'>
array2d.:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
array2d[0:2, 0:2]:
 [[1 2]
 [4 5]]
----------------------------------------
array2d[1:3, 0:3]:
 [[4 5 6]
 [7 8 9]]
----------------------------------------
array2d[1:3, :]:
 [[4 5 6]
 [7 8 9]]
----------------------------------------
array2d[:, :]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:3, 0:3]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
array2d[:2, 1:]:
 [[2 3]
 [5 6]]
array2d[0:2, 1:3]:
 [[2 3]
 [5 6]]
array2d[:2, 0].shape: (2,)
array2d[:2, 0].shape : (2,)
array2d[0:2, 0].:
 [1 4]
