### Numpy ndarray
* ndarray 생성하기 - np.array()

In [ ]:
import numpy as np

In [ ]:
list1 = [1, 2, 3]
print("list1 :",list1)
print("list1 :",type(list1))

array1 = np.array(list1)
print("array1 :",array1)
print("array1 :",type(array1))

* ndarray의 shape(형태-배열의 구조) / 차원(일차원, 이차원, 삼차원, .....)

In [ ]:
# 일차원 배열

array1 = np.array([1, 2, 3, 4, 5])
print("array1       :",array1)
print("array1 타입  :",type(array1))
print("array1 shape :",array1.shape)

In [ ]:
# 이차원 배열
array2 = np.array([
                   [1, 2, 3],
                   [4, 5, 6]
                 ])
print("array2       :\n",array2)
print("array2 타입  :",type(array2))
print("array2 shape :",array2.shape)

In [ ]:
# 이차원 배열

array3 = np.array([[1, 2, 3, 4, 5]])
print("array3       :",array3)
print("array3 타입  :",type(array3))
print("array3 shape :",array3.shape)

In [ ]:
print(f"array1 : {array1.ndim} 차원\narray2 : {array2.ndim} 차원\narray3 : {array3.ndim} 차원")

* ndarray 속에 들어있는 값의 data type - ndrray.dtype

In [ ]:
list1 = [1, 2, 3, 4, 5]
print("list1 :",list1)
print("list1 :",type(list1))

array1 = np.array(list1)
print("array1 :",array1)
print("array1 :",type(array1))
print("array1 속에 들어있는 값의 data type :",array1.dtype)

* ndarray 속에 들어있는 값의 타입 변환하기 - astype() 메소드 사용

In [ ]:
array_int   = np.array([1, 2, 3, 4, 5])
array_float = array_int.astype("float64")

print("array_int         :",array_int)
print("array_int d타입   :",array_int.dtype)
print("array_float       :",array_float)
print("array_float d타입 :",array_float.dtype)

In [ ]:
# array_float = array_int.astype("float64")
array_int2 = array_float.astype("int32")

print("array_int2        :",array_int2)
print("array_int2 d타입  :",array_int2.dtype)

In [ ]:
array_float2 = np.array([1.2, 2.3, 3.4, 4.5])
print("array_float2       :",array_float2)
print("array_float2 d타입 :",array_float2.dtype)

array_int3 = array_float2.astype("int32")
print("array_int3         :",array_int3)
print("array_int3 d타입   :",array_int3.dtype)

### 이차원 배열의 요소들을 axis 를 지정해서 연산하기
* axis=0 : 행이 축이 됨
* axis=1 : 열이 축이 됨

In [ ]:
array2 = np.array([
                   [1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10]
                  ])
print("array2.sum()       :",array2.sum())
print("array2.sum(axis=0) :",array2.sum(axis=0))
print("array2.sum(axis=1) :",array2.sum(axis=1))

### ndarray 생성하는 여러가지 방법들
* np.arange() 
* np.zeros()
* np.pones()

In [ ]:
# arange()

range_array = np.arange(10)
print("range_array       :",range_array)
print("range_array shape :",range_array.shape)
print("range_array dtype :",range_array.dtype)

In [ ]:
# zeros()

zero_array = np.zeros((3, 3), dtype="int32")
print("zero_array       :\n",zero_array)
print("zero_array shape :",zero_array.shape)
print("zero_array dtype :",zero_array.dtype)

In [ ]:
zero_array = np.zeros((3, 3))
print("zero_array       :\n",zero_array)
print("zero_array shape :",zero_array.shape)
print("zero_array dtype :",zero_array.dtype)

In [ ]:
# ones()

ones_array = np.ones((3, 6))
print("ones_array       :\n",ones_array)
print("ones_array shape :",ones_array.shape)
print("ones_array dtype :",ones_array.dtype)

In [ ]:
ones_array = np.ones((3, 6), dtype="int32")
print("ones_array       :\n",ones_array)
print("ones_array shape :",ones_array.shape)
print("ones_array dtype :",ones_array.dtype)

* ndarray.reshape() 메소드 - shape 를 재설정함

In [ ]:
array1 = np.arange(10)
print("array1 :\n",array1)

array2 = array1.reshape(2, 5)
print("array2 :\n",array2)

array3 = array1.reshape(5, 2)
print("array3 :\n",array3)

#  데이터 개수에 맞는 행과 열을 지정해 주어야만 함
# ValueError: cannot reshape array of size 10 into shape (3,3)
# array4 = array1.reshape(3, 3)
# print("array4 :\n",array4)

### reshape() 의 argument 로 -1 설정하기
* argument 둘 다 -1 로 지정할 수는 없음

In [ ]:
array1 = np.arange(10)
print("array1 의 shape :\n",array1.shape)
print("array1 :\n",array1)

# reshape(-1, 5) :  2 X 5 
# 열을 5로 지정하고 행은 이에 맞추어서 자동으로 지정됨
array2 = array1.reshape(-1, 5)
print("array2 의 shape :\n",array2.shape)
print("array2 :\n",array2)

# reshape(5, -1) : 5 X 2
# 행을 5로 지정하고 열은 이에 맞추어서 자동으로 지정됨
array3 = array1.reshape(5, -1)
print("array3 의 shape :\n",array3.shape)
print("array3 :\n",array3)

In [ ]:
# 1 차원 배열
array1 = np.arange(5)
print("array1 의 shape :\n",array1.shape)
print("array1 :\n",array1)

# 5 X 1 의 2 차원 배열
array2 = array1.reshape(-1, 1)
print("array2 의 shape :\n",array2.shape)
print("array2 :\n",array2)

# 2 차원 배열을 1 차원 배열로 변환홤
array3 = array2.reshape(-1, )
print("array3 의 shape :\n",array3.shape)
print("array3 :\n",array3)

### ndarray  에서 indexing 하기

In [ ]:
array1 = np.arange(10)
print("array1 :\n",array1)

array1_1 = np.arange(start=1, stop=10)
print("array1_1 :\n",array1_1)

array1_2 = np.arange(1, 10)
print("array1_2 :\n",array1_2)

In [ ]:
array1_2 = np.arange(1, 10)

result = array1_2[2]
print("result :",result)
print("result :",type(result))

result2 = array1_2[-1]
print("result2 :",result2)
result3 = array1_2[-2]
print("result3 :",result3)

print("array1_2 :\n",array1_2)

array1_2[0] = 9
array1_2[8] = 1
print("array1_2 :\n",array1_2)

In [ ]:
# reshape() 를 사용해서 2 차원 배열로 변환하기
array1_2_2d = array1_2.reshape(3, 3)
'''
array1_2_2d
 [[9 2 3]
 [4 5 6]
 [7 8 1]]
'''
print("array1_2_2d[0, 0] :",array1_2_2d[0, 0])
print("array1_2_2d[1, 1] :",array1_2_2d[1, 1])
print("array1_2_2d[2, 2] :",array1_2_2d[2, 2])
print("array1_2_2d[0, 2] :",array1_2_2d[0, 2])
print("-" * 40)

print("array1_2_2d[0][0] :",array1_2_2d[0][0])
print("array1_2_2d[1][1] :",array1_2_2d[1][1])
print("array1_2_2d[2][2] :",array1_2_2d[2][2])
print("array1_2_2d[0][2] :",array1_2_2d[0][2])
print("-" * 40)

print("array1_2_2d :\n",array1_2_2d)
print("array1_2_2d의 shape :",array1_2_2d.shape)
print("-" * 40)

### ndarray  에서 slicing 하기

In [ ]:
array1 = np.arange(1, 10)
print("array1.shape :", array1.shape)
print("array1 type  :", type(array1))
print("array1 :\n", array1)
print("-" * 40)

array2 = array1[0:3]
print("array2.shape :", array2.shape)
print("array2 type  :", type(array2))
print("array2 :\n", array2)
print("-" * 40)

array3 = array1[:3]
print("array3.shape :", array3.shape)
print("array3 type  :", type(array3))
print("array3 :\n", array3)
print("-" * 40)

array4 = array1[3:]
print("array4.shape :", array4.shape)
print("array4 type  :", type(array4))
print("array4 :\n", array4)
print("-" * 40)

array5 = array1[:]
print("array5.shape :", array5.shape)
print("array5 type  :", type(array5))
print("array5 :\n", array5)
print("-" * 40)

In [ ]:
array2d = array1.reshape(3, 3)
print("array2d.shape :", array2d.shape)
print("array2d type  :", type(array2d))
print("array2d :\n", array2d)
print("-" * 40)

# 1, 2, 행 X 1, 2 열
print("array2d[0:2, 0:2] :\n",array2d[0:2, 0:2])
print("-" * 40)

# 1, 2 행 X 1, 2, 3 열
print("array2d[1:3, 0:3] :\n",array2d[1:3, 0:3])
print("-" * 40)

# 1, 2 행 X 1, 2, 3 열 : 시작과 끝을 생략하면 처음부터 끝까지
print("array2d[1:3, :] :\n", array2d[1:3, :])
print("-" * 40)

# 1, 2, 3 행 X 1, 2, 3 열 : 시작과 끝을 생략하면 처음부터 끝까지
print("array2d[:, :] :\n",array2d[:, :])
print("array2d[0:3, 0:3] :\n",array2d[0:3, 0:3])
print("-" * 40)

# 1, 2 행 X 2, 3 열
print("array2d[:2, 1:] :\n",array2d[:2, 1:])
print("array2d[0:2, 1:3] :\n",array2d[0:2, 1:3])
print("-" * 40)

# 1, 2 행 X 1 열 : 열을 하나만 지정하면 1 차원 배열로 됨
print("array2d[:2, 0].shape  :",array2d[:2, 0].shape)
print("array2d[0:2, 0].shape :",array2d[0:2, 0].shape)
print("array2d[:2, 0] :\n",array2d[:2, 0])