In [2]:
import numpy as np

In [3]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print("array2d :\n",array2d)
print("-" * 40)

array3 = array2d[[0, 1], 2]
print("array3 :\n",array3)
print("array2d[[0, 1], 2] :\n",array2d[[0, 1], 2])
print("-" * 40)

array4 = array2d[[0, 2], 0:2]
print("array4 :\n",array4)
print("array2d[[0, 2], 0:2] :\n",array2d[[0, 2], 0:2])
print("-" * 40)

array5 = array2d[[0, 1]]
print("array5 :\n",array5)
print("array2d[[0, 1]] :\n",array2d[[0, 1]])
print("-" * 40)

array6 = array2d[[0, 1], :]
print("array6 :\n",array6)
print("array2d[[0, 1], :] :\n",array2d[[0, 1], :])

array2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
array3 :
 [3 6]
array2d[[0, 1], 2] :
 [3 6]
----------------------------------------
array4 :
 [[1 2]
 [7 8]]
array2d[[0, 2], 0:2] :
 [[1 2]
 [7 8]]
----------------------------------------
array5 :
 [[1 2 3]
 [4 5 6]]
array2d[[0, 1]] :
 [[1 2 3]
 [4 5 6]]
----------------------------------------
array6 :
 [[1 2 3]
 [4 5 6]]
array2d[[0, 1], :] :
 [[1 2 3]
 [4 5 6]]


In [4]:
array1d = np.arange(10)
print(array1d)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
print(array1d > 5)
result_bool = array1d > 5
print("result_bool : \n", result_bool)
print("result_bool : \n", type(result_bool))

[False False False False False False  True  True  True  True]
result_bool : 
 [False False False False False False  True  True  True  True]
result_bool : 
 <class 'numpy.ndarray'>


In [6]:
print("array1d(원래의 배열) :\n",array1d)
array3 = array1d[array1d >5]
print("array3 (Boolean Indexing - [array1d > 5]):\n",array3)

array1d(원래의 배열) :
 [0 1 2 3 4 5 6 7 8 9]
array3 (Boolean Indexing - [array1d > 5]):
 [6 7 8 9]


In [9]:
boolean_indexes_array = \
    np.array([False, False, False, False, False, False, True, True, True, True])
'''
array1d (원래의 배열) :
 [0 1 2 3 4 5 6 7 8 9]
'''
array3 = array1d[boolean_indexes_array]

In [16]:
indexes_array = np.array([5, 6, 7, 8])
print("indexes_array :\n",indexes_array)
'''
array1d (원래의 배열) :
 [0 1 2 3 4 5 6 7 8 9]
'''
array4 = array1d[indexes_array]
print("array4 :\n",array4)
print("-" * 40)

indexes_array = np.array([5, 6, 7, 8])
print("indexes_array :\n",indexes_array)
array1d = np.arange(1, 10)
array5 = array1d[indexes_array]
print("array5 :\n",array5)

indexes_array :
 [5 6 7 8]
array4 :
 [6 7 8 9]
----------------------------------------
indexes_array :
 [5 6 7 8]
array5 :
 [6 7 8 9]


In [18]:
array1d = np.arange(1, 10)
print("array1d :\n",array1d)
result = []
for i in range(0,9):
    if array1d[i] > 5:
        result.append(array1d[i])
result_array = np.array(result)
print("result_array :\n",result_array)
print("array1d[array1d > 5] :\n",array1d[array1d > 5])

array1d :
 [1 2 3 4 5 6 7 8 9]
result_array :
 [6 7 8 9]
array1d[array1d > 5] :
 [6 7 8 9]


In [20]:
origin_array = np.array([3, 1, 9, 5])
print("원래의 배열 :\n", origin_array)

print("-- np.sort() 함수로 정렬하기 : 원래의 배열이 변형되지 않음 --")
print("-- 정렬된 배열이 새로 생성됨 --")
sort_array1 = np.sort(origin_array)
print("원래의 배열 :\n",origin_array)
print("sort_array1 :\n",sort_array1)
print()

print("-- ndarray 의 sort() 메소드로 정렬하기 : 원래의 배열이 변형됨 --")
print("-- 정렬된 배열을 새로 생성하지 않음 --")
sort_array2 = origin_array.sort()
print("원래의 배열 :\n",origin_array)
print("sort_array2 :\n",sort_array2)

원래의 배열 :
 [3 1 9 5]
-- np.sort() 함수로 정렬하기 : 원래의 배열이 변형되지 않음 --
-- 정렬된 배열이 새로 생성됨 --
원래의 배열 :
 [3 1 9 5]
sort_array1 :
 [1 3 5 9]

-- ndarray 의 sort() 메소드로 정렬하기 : 원래의 배열이 변형됨 --
-- 정렬된 배열을 새로 생성하지 않음 --
원래의 배열 :
 [1 3 5 9]
sort_array2 :
 None


In [21]:
sort_array1_descending = np.sort(origin_array)[::-1]
print("sort_array1_descending :\n",sort_array1_descending)

sort_array1_descending :
 [9 5 3 1]


In [22]:
array2d = np.array([[8, 20], 
                    [5, 2]])
sort_array2d_row = np.sort(array2d, axis=0)
print("행방향(행이 축이 됨) 정렬 :\n",sort_array2d_row)
sort_array2d_col = np.sort(array2d, axis=1)
print("열방향(열이 축이 됨) 정렬 :\n",sort_array2d_col)

행방향(행이 축이 됨) 정렬 :
 [[ 5  2]
 [ 8 20]]
열방향(열이 축이 됨) 정렬 :
 [[ 8 20]
 [ 2  5]]


In [24]:
origin_array = np.array([3, 1, 9, 5])
print("원래의 배열 :\n",origin_array)
print("원래의 index :\n",np.array([0, 1, 2, 3]))
sort_array = np.sort(origin_array)
print("sort_array (정렬된 숫자들) :\n",sort_array)
argsort_indexes_array = np.argsort(origin_array)
print("argsort_indexes_array (정렬되기 전 숫자들의 index) :\n",argsort_indexes_array)

원래의 배열 :
 [3 1 9 5]
원래의 index :
 [0 1 2 3]
sort_array (정렬된 숫자들) :
 [1 3 5 9]
argsort_indexes_array (정렬되기 전 숫자들의 index) :
 [1 0 3 2]


In [25]:
origin_array = np.array([6, 3, 8, 2])
print("원래의 행렬 :\n",origin_array)
print("원래의 인덱스 :\n",np.array([0, 1, 2, 3]))
print("내림차순 정렬 :\n",np.sort(origin_array)[::-1])
print("정렬전 숫자들의 자리에 재배치된 인덱스")
print(np.argsort(origin_array)[::-1])

원래의 행렬 :
 [6 3 8 2]
원래의 인덱스 :
 [0 1 2 3]
내림차순 정렬 :
 [8 6 3 2]
정렬전 숫자들의 자리에 재배치된 인덱스
[2 0 1 3]


In [26]:
student_array = np.array(["이순신", "강감찬", "대조영", "유관순", "안중근"])
score_array   = np.array([85, 92, 84, 99, 76])
print("score_array (원본) :\n",score_array)
print("원본 인덱스 :\n",np.array([0, 1, 2, 3, 4]))
sort_score   = np.sort(score_array)
print("sort_score  (정렬) :\n",sort_score)
sort_score_descending = np.sort(score_array)[::-1]
print("sort_score_descending  (내림차순) :\n",sort_score_descending)
sort_indexes = np.argsort(score_array)
print("sort_indexes :\n",sort_indexes)
print("-" * 40)
print("-- 성적 오름차순으로 이름 출력하기 --")
print(student_array[sort_indexes])
print("-" * 40)
print("-- 성적 내림차순으로 이름 출력하기 --")
sort_indexes_descending = np.argsort(score_array)[::-1]
print(student_array[sort_indexes_descending])
print("-" * 40)


score_array (원본) :
 [85 92 84 99 76]
원본 인덱스 :
 [0 1 2 3 4]
sort_score  (정렬) :
 [76 84 85 92 99]
sort_score_descending  (내림차순) :
 [99 92 85 84 76]
sort_indexes :
 [4 2 0 1 3]
----------------------------------------
-- 성적 오름차순으로 이름 출력하기 --
['안중근' '대조영' '이순신' '강감찬' '유관순']
----------------------------------------
-- 성적 내림차순으로 이름 출력하기 --
['유관순' '강감찬' '이순신' '대조영' '안중근']
----------------------------------------


In [ ]:
array1 = np.arange(1, 10)
print(array1)
print(array1[np.array([5, 6, 7, 8])])

In [28]:
array_a = np.array([[1, 2, 3],
                    [4, 5, 6]])

array_b = np.array([[7, 8], 
                    [9, 10], 
                    [11, 12]])

product_array = np.dot(array_a, array_b)
print("행렬의 내적 :\n",product_array)

행렬의 내적 :
 [[ 58  64]
 [139 154]]


In [ ]:
array_a = np.array([[1, 2], 
                    [3, 4], 
                    [5, 6]])
print("array_a :\n",array_a)

transpose_matrix = np.transpose(array_a)
print("array_a 의 전치행렬 :\n",transpose_matrix)

In [29]:
array_a = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
print("array_a :\n",array_a)

transpose_matrix = np.transpose(array_a)
print("array_a 의 전치행렬 :\n",transpose_matrix)

array_a :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array_a 의 전치행렬 :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
